version: '3'

services:
    mongodb:
            image: mongo:4.4.0
            container_name: "mongodb"
            environment:
              MONGO_DATA_DIR: /data/db
            ports:
                - 27017:27017
            volumes:
                - ./data:/data/db:rw
    mongo-express:
        image: mongo-express
        container_name: mongoexpress
        restart: always
        ports:
          - 8081:8081
        environment:
            ME_CONFIG_MONGODB_SERVER: mongodb
            ME_CONFIG_MONGODB_PORT: 27017